---
#
# edX Configuration
#
# github:     https://github.com/llasha/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/llasha/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role add_user
#

# Allow this role to be duplicated in dependencies
allow_duplicates: yes
